## Travis file ##

sudo: required

services:
	- docker

before_install:
	- docker build -t arajkumar14/docker-react -f Dockerfile.dev .

script:
	- docker run arajkumar14/docker-react npm run test -- --coverage




